### ISSUE TITLE
router.push()??

### ISSUE THREAD

**Issue by sgoveia** [KingPixil/moon-router#17]
Loving Moon!! You should be very proud @kbrsh ! 

Just curious about programmatically transitioning, similar to the Vue.js router.push("/home") as an example. https://router.vuejs.org/en/essentials/navigation.html

Basically after a "button" click inside a method function I want to route.. instead of an explicit link..

Again great work!

**Comment by kbrsh** [comment]
Thanks! Glad you like Moon @sgoveia!

In the next version, the router will come with a `router.navigate` method that does exactly that—change the route programmatically. It is also the function used internally by router links.

**Comment by sgoveia** [comment]
@kbrsh Awesome! Thanks for the expeditious response! Of course,  I have to ask eta on "next version"...  :)

**Comment by kbrsh** [comment]
Haha the next version is v1 for all Moon modules (moon, router, monx) and should be released in the coming months. Also, I'm closing this issue since it has already been added.
