### ISSUE TITLE
<router-view></router-view> in component not working

### ISSUE THREAD

**Issue by shellvip** [KingPixil/moon-router#3]
I use `<router-view></router-view> `in a .moon file but then the `<router-link>` not working(when clicked, the window location has changed but the page not update)

should `<router-view>`can be only used in the root moon element?

**Comment by kbrsh** [comment]
For compiling of `.moon` files, I'm assuming you are using `moonify`. What version of `moonify`, `moon-router`, and `moonjs` are you using?

**Comment by shellvip** [comment]
"moon-router": "0.0.5"
"moonjs": "0.10.0"
"moonify": "0.0.12"

**Comment by kbrsh** [comment]
Will be fixed in Moon v0.11.0, and moon-router 0.0.6.

It will be working with those two versions (coming soon), as long as the router is installed to the root Moon instance (via the `router` option).
