### ISSUE TITLE
Using Webpack

### ISSUE THREAD

**Issue by findborg** [KingPixil/moon-router#4]
Could you put together a very basic example using webpack?  
Maybe three link example.  Two pages with the second with an update able section.
I thought I had seen one somewhere but can't find it now.

**Comment by findborg** [comment]
It installed fine with the package json.  But,  I am having problems getting it to work.

**Comment by kbrsh** [comment]
I'll work on an example. Can you let me know what exactly isn't working?

**Comment by kbrsh** [comment]
`package.json`

```js
{
  "name": "moon-moon-router-webpack-example",
  "version": "1.0.0",
  "description": "Moon + Moon-Router + Webpack",
  "main": "scripts.js",
  "dependencies": {
    "moon-router": "0.0.5",
    "moonjs": "^0.10.0"
  },
  "devDependencies": {
    "webpack": "^2.6.1"
  }
}
```

`webpack.config.js`

```js
module.exports = {
  entry: './scripts.js',
  output: {
    filename: 'bundle.js'
  }
}
```

`index.html`

```html
<!DOCTYPE html>
<html>
<head>
	<title>Moon + Moon Router + Webpack</title>
</head>
<body>
	<div id="app">
		<ul>
			<li><router-link to="/">Home</router-link></li>
			<li><router-link to="/about">About</router-link></li>
			<li><router-link to="/contact">Contact</router-link></li>
		</ul>
		<router-view></router-view>
	</div>
	<script type="text/javascript" src="./bundle.js"></script>
</body>
</html>
```

`scripts.js`

```js
const Moon = require("moonjs");
const MoonRouter = require("moon-router");

Moon.use(MoonRouter);

const router = new MoonRouter({
	"default": "/",
	"map": {
		"/": "Home",
		"/about": "About",
		"/contact": "Contact"
	}
});

Moon.component("Home", {
	template: "<div><h1>Home</h1></div>"
});

Moon.component("About", {
	template: "<div><h1>About</h1></div>"
});

Moon.component("Contact", {
	template: "<div><h1>Contact</h1></div>"
});

new Moon({
	el: "#app",
	router
});
```

Build with `webpack`

**Comment by findborg** [comment]
Ok thanks,  I was having problems getting the script.js written correctly.  I am going to get this working and practice some more.  My next question will be about component importing,  I see here that you have the "template" /HTML calls built into script.js  I think you have something written about that in the docs.  I will look it up.

**Comment by findborg** [comment]
This works perfectly,  Only took a sec to get it going.

**Comment by findborg** [comment]
FYI I am using the header component example,  so maybe you could show me how to pull a different header component in for home and and another header for about and contact?

**Comment by kbrsh** [comment]
Awesome! I'm not sure what you mean by pulling a different header component, but you can use slots as you would in Vue (not documented in Moon yet, but they work), or props (as used in the example) to change the text of the header.

**Comment by findborg** [comment]
I'm sorry,  I want to be able to work with the .moon like this
```
<template>
<div>


  <h1>{{content}}</h1>
  <img src="/assets/fb-homepage-flag.png">
  <p>This is starter code for a multi-page app.</p>
</div>  
</template>
<style scoped>

  h1 {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;
    font-weight: 200;
    font-size: 100px;
    color: #111;
    
  }
  
</style>
<script>
  exports = {
    props: ['content']
  }
</script>
```

**Comment by kbrsh** [comment]
That should be working...what exactly is wrong with it?

**Comment by findborg** [comment]
It does work,  but in the script.js file that we have now for the pages it has this:
```
Moon.component("Home", {
	template: "<div><h1>Home</h1></div>"
});
 ```
I want to be able to import or require the header.moon  in the page not "home"
you know like /home should load index.moon and so on..

**Comment by kbrsh** [comment]
Ahh, you want to use the header component in the router components. You can actually define your router components (`home`, `about`, `contact`) with `.moon` files. `.moon` files export a function that takes one parameter--Moon. It will register the component there.

You can do this:

`home.moon`

```html
<template>
  <div>
    <header content="Home"></header>
  </div>
</template>
```

`scripts.js`

```js
// at the top of the file...
require("./components/header.moon")(Moon); // register header
require("./components/home.moon")(Moon); // register home
```

That way you don't have to define your components in the `scripts.js` file, but instead you register them with `.moon` files.

By the way, component names are determined by their file name (or alternatively a `name` option). They are also case sensitive.

**Comment by findborg** [comment]
Let me see if I can get this working,
PS,  I am loving this project of yours and thanks for the help.

**Comment by kbrsh** [comment]
No problem, glad you like it!

**Comment by findborg** [comment]
so do I just change this:
```
Moon.component("Home", {
	template: "<div><h1>Home</h1></div>"
});
```
to this?
```
Moon.component("Home", {
	
});
```

**Comment by kbrsh** [comment]
Nope, you would just remove it all together, as the `.moon` file will register the component for you.

**Comment by findborg** [comment]
oh crazy easy,  let me try

**Comment by findborg** [comment]
I am doing something wrong:
```
require("./js/components/home.moon")(Moon); // register header

const Moon = require("moonjs");
const MoonRouter = require("moon-router");

Moon.use(MoonRouter);

const router = new MoonRouter({
	"default": "/",
	"map": {
		"/": "home.moon",
		"/about": "About",
		"/contact": "Contact"
	}
});



Moon.component("About", {
	template: "<div><h1>About Findborg</h1></div>"
});

Moon.component("Contact", {
	template: "<div><h1>Contact</h1></div>"
});

new Moon({
	el: "#app",
	router
});

**Comment by kbrsh** [comment]
You should register the header _and_ home components (at least if you are using the header component), and you should add the `require` lines after including Moon and Moon-Router. Sorry if I didn't make that clear.

Next, change your map back to `"/": "home"`, as it is mapping a route to the component, which is named after the file name, excluding the extension.

**Comment by findborg** [comment]
YES!!  I got it.

**Comment by findborg** [comment]
Here is what I have so others can see the simple require function:
```
/*=============================
  Primary Application Code
=============================*/


const Moon = require("moonjs");
const MoonRouter = require("moon-router");

require("./components/home.moon")(Moon); // register header


Moon.use(MoonRouter);

const router = new MoonRouter({
	"default": "/",
	"map": {
		"/": "home",
		"/about": "About",
		"/contact": "Contact"
	}
});



Moon.component("About", {
	template: "<div><h1>About Findborg</h1></div>"
});

Moon.component("Contact", {
	template: "<div><h1>Contact</h1></div>"
});

new Moon({
	el: "#app",
	router
});

**Comment by kbrsh** [comment]
Awesome!

**Comment by findborg** [comment]
Sorry so long since last seen.  Anyway,  I am back playing with this.  I created an About.moon component so that I could just require it instead of trying to do it in one file.  However, it is not loading.  Have a look.
```
/*=============================
  Primary Application Code
=============================*/


const Moon = require("moonjs");
const MoonRouter = require("moon-router");

require("./components/home.moon")(Moon); // register header
require("./components/About.moon")(Moon);

Moon.use(MoonRouter);

const router = new MoonRouter({
	"default": "/",
	"map": {
		"/": "home",
		"/about": "About",
		"/contact": "Contact"
	}
});





Moon.component("Contact", {
	template: "<div><router-link to=\"/about\">About</router-link><h1>Contact</h1></div>"
});

new Moon({
	el: "#app",
	router
});
```
@kbrsh
