### ISSUE TITLE
Passing Props into router view?

### ISSUE THREAD

**Issue by findborg** [KingPixil/moon-router#5]
I was wondering,  I keep getting not defined for the h1
```
<Header content="Findborg"></Header>
```
I am trying to use the prop in the index page,  I tried placing the above between the ```<router-view></router-view> ```  which was a kinda hack I used with vue.  But,  it will not work for me now.  Can you show me a better way to do this using the router?

**Comment by findborg** [comment]
![ice_screenshot_20170615-144210](https://user-images.githubusercontent.com/6894779/27198691-e7d7a2ee-51d8-11e7-8398-cbfd4b0b9006.png)

**Comment by kbrsh** [comment]
`<router-view>` will ignore everything passed to it, and will simply display the current component mapped to the current route.

Put the `<header>` element *inside* of whatever component you want to render it in, and if you'd like it to appear in all of the pages, then place it outside of the `<router-view>`

**Comment by findborg** [comment]
Kinda figured that would be the case.  I will have to try and figure out a different way.  But,  no problem thanks for looking into this.

**Comment by kbrsh** [comment]
What exactly are you trying to achieve? I'll be glad to help you out.

**Comment by findborg** [comment]
Well think of a pre-built multi page template where a novice user could just fill in the blanks using props or slots.  This is easy to do with no route.  But,  like you said,  a permanent header footer nav would solve that problem.  I guess what we need to do is build a paging component that will be able to except slots and or props.  Kinda like tabs.

**Comment by kbrsh** [comment]
Got it, so you are trying to implement some sort of navigation that changes depending on the current route.

You can make a navigation component that changes according to the current route.

**Comment by findborg** [comment]
Not exactly,  you are thinking strictly in js.  I understand what you are saying.
My main thing about this is that most of my projects are built using php.  So I have to use props/slots for components that I want to build (mostly for templating and page layout).  I know it would seem like a hack to you.  But,  some of us have to work with what we got.  ha.  Anyway,  props and slots are what drew me to Vue.  I could build a component and pass php to it.  This gets real tricky when you try to use all the benefits of using something like webpack,  etc.   Don't worry to much about this.  I will need you help when I attempt to learn the json response stuff. wink wink.

**Comment by findborg** [comment]
So to get back on topic,  there is no way to use props or slots from the index page when using the router unless you build components that are surrounding or outside of the router tag.

**Comment by findborg** [comment]
Actually,  now that I think about it,  that is how I did it with Vue,  I would build into the loaded page view some scoped css to hide parts of the page as the dynamic route changed.  That is how I got it to wok with php.

**Comment by kbrsh** [comment]
What were you doing with Vue that didn't work with Moon? There is usually an alternative or a working way to replicate it.

**Comment by raqbit** [comment]
After looking at this issue I am still not sure how I would tackle passing props into my routed components.

My situation:
I have a timer that is started in the instance's init hook (destroyed in its destroy hook). 
This timer calls a method on the instance, which will get the current hour & minute, and set some properties on the instance to these values. Now I want to have a component which is able to render these hour/minutes variables via computed properties (Adds a leading zero and calculates am/pm for a 12h time display).
How would I pull this off?

**Comment by kbrsh** [comment]
@Raqbit You can try passing data through query parameters or named parameters, and access them like:

```js
{
  props ["route"],
  methods: {
    test() {
      console.log(this.get("route").query);
    }
  }
}
```
