### ISSUE TITLE
How can I change the active class of a router link?

### ISSUE THREAD

**Issue by findborg** [KingPixil/moon-router#6]
Title says it all.  But,  we need to be able to at the very least be able to change the active and hover classes.

**Comment by findborg** [comment]
In the vue router you can just add a line when you call the routes,  default is something like is-active and you could change this to whatever you need like is-on etc

**Comment by kbrsh** [comment]
Agreed, I'll add this.

**Comment by kbrsh** [comment]
Should be fixed in v0.1.1.
