### ISSUE TITLE
History API

### ISSUE THREAD

**Issue by vrgenl** [KingPixil/moon-router#7]
Hi is it possible to have the HTML5 history API so the user wont see the /#/path in the address bar?

**Comment by kbrsh** [comment]
Hey, this is actually a planned feature, it should be coming in the next version.

**Comment by vrgenl** [comment]
Sweet! Thanks for blazing fast replies every single time ;)

**Comment by kbrsh** [comment]
Haha no problem, I'm usually on at this time.
